version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Hd115t42
       MYSQL_DATABASE: wordpressDev
       MYSQL_USER: wordpressDev
       MYSQL_PASSWORD: wordpressDev

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpressDev
       WORDPRESS_DB_PASSWORD: wordpressDev
       WORDPRESS_DB_NAME: wordpressDev
volumes:
    db_data: {}